### ISSUE TITLE
나이스페이 에러코드 리스트

### ISSUE THREAD

**Issue by joohyuck** [open-transit/noondo.kr#38]
result code 중 F*** (fuck아님_) 형식의 에러코드가 확인되지 않음

**Comment by joohyuck** [comment]
@thechunsik  춘식님 이건 나이스페이 모듈에서
resultCode 랑 resultMsg 를 같이 반환해주는데, 그럼 차라리 resultMsg를 가져와서 알림으로 띄워줄까요 ??

**Comment by thechunsik** [comment]
응 status, msg 이 두개가 오고있는데 msg를 code로 고치고 msg에 그 메시지를 담아서 보내주면 좋을듯
