### ISSUE TITLE
뉴스피드, 사용자 탑승 취소하면 과거에 "신청했습니다" 피드 삭제

### ISSUE THREAD

**Issue by Yeyeon** [open-transit/noondo.kr#49]

**Comment by thechunsik** [comment]
탑승을 취소했습니다라는 피드를 추가하는게 자연스럽지 않나?

**Comment by Yeyeon** [comment]
취소한게 너무 많이 보이면 안좋을거같아서 취소하면 피드에서 사라지는걸 생각했는데..취소 피드가 나으려나? 신청이 있으면 취소가 나을수도 있겠다 우선 취소피드로!

**Comment by thechunsik** [comment]
취소 피드 등록됨
