### ISSUE TITLE
1,2교시 통합노선 텍스트

### ISSUE THREAD

**Issue by thechunsik** [open-transit/noondo.kr#53]
노선화면, 결제화면 종합 텍스트 @Yeyeon @joohyuck

**Comment by Yeyeon** [comment]
1) 통합노선

[신청]
이 노선은 이른아침과 늦은아침이 통합합되어 제공되는 노선으로 원하시는 요일 별 탑승 시간을 자유롭게 선택하실 수 있습니다. 요일별 출석체크를 위해 요일별 탑승시간을 정확히 체크해주세요. 

[결제]

체크/신용카드 결제만 가능합니다. 신청 시에는 결제 되지않으며 목표 인원이 모여 모집에 성공하면 출금됩니다. 모집에 실패한 경우 결제는 진행되지 않습니다.



2) 1/2교시 노선

[신청] 
이 노선은 1/2교시 모두 운행하고 있는 노선입니다. 2교시 노선은 모집이 인원 미달로 실패할 경우, 아예 못 타게 되는 것보다 더 일찍 1교시 노선을 이용하고자 희망하는 신청자를 대상으로 '1교시 노선 자동 신청' 기능을 제공하고 있습니다. 2교시 노선을 신청하시는 분들께서는 자동 신청 기능 여부를 꼭 체크해주세요.

따라서 1교시 노선은 2교시 노선 모집이 실패 할 경우, 2교시 노선에서 1교시로 옮겨 온 대체 신청자로 인해 후반부에 모집 성공 확률이 더 높아질 수 있습니다.  

[결제]

체크/신용카드 결제만 가능합니다. 신청 시에는 결제 되지않으며 목표 인원이 모여 모집에 성공하면 출금됩니다. 모집에 실패한 경우 결제는 진행되지 않습니다.

**Comment by Yeyeon** [comment]
결제 페이지 공지 메세지는 요걸 확인하면 된다! 춘식님
